// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmithSwimmingSchoolApp.Data;

#nullable disable

namespace SmithSwimmingSchoolApp.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241218222749_m1")]
    partial class m1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "2",
                            Name = "Coach",
                            NormalizedName = "COACH"
                        },
                        new
                        {
                            Id = "3",
                            Name = "Swimmer",
                            NormalizedName = "SWIMMER"
                        },
                        new
                        {
                            Id = "4",
                            Name = "Visitor",
                            NormalizedName = "VISITOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "100",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "101",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "102",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "107",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "108",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "109",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "110",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "103",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "104",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "105",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "106",
                            RoleId = "3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SmithSwimmingSchoolApp.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "100",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "10c8f5ca-8973-4c7c-8c5c-30a4d0f78b74",
                            Email = "admin@3s.com",
                            EmailConfirmed = true,
                            FullName = "Administrator",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@3S.COM",
                            NormalizedUserName = "ADMIN@3S.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGwEz0QdXB+ALjuSLziFQrvvk2Dzf7JdLD3RGubdsmqmHKQXT7KAhBXjU78MhnZB8A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2d64aeb1-bcaf-455b-a665-cbfa1819e3c6",
                            TwoFactorEnabled = false,
                            UserName = "admin@3s.com"
                        },
                        new
                        {
                            Id = "101",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0a1e205b-0c6b-4bd8-aea4-9be5f5d196e2",
                            Email = "johnsmith@3s.com",
                            EmailConfirmed = true,
                            FullName = "John Smith",
                            LockoutEnabled = false,
                            NormalizedEmail = "JOHNSMITH@3S.COM",
                            NormalizedUserName = "JOHNSMITH@3S.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKAo6FUDbLCesfrEfVmexdbRkff4e8mkkXo86hKbgifRZiWjIhE9dFMsZOxa78/bVg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c1dcf93d-5182-44f4-9073-663159d60a47",
                            TwoFactorEnabled = false,
                            UserName = "johnsmith@3s.com"
                        },
                        new
                        {
                            Id = "102",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "95afee3b-56c7-4eff-a341-554a49866983",
                            Email = "aliceaohnson@3s.com",
                            EmailConfirmed = true,
                            FullName = "Alice Johnson",
                            LockoutEnabled = false,
                            NormalizedEmail = "ALICEJOHNSON@3S.COM",
                            NormalizedUserName = "ALICEJOHNSON@3S.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEL2cmklYPOTU/UoTADoqZSgsVvC3j+AfwfKyfgxFy+YygH/5CfgIQiHYQlJ8QZmHA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b1c47b8b-0ade-4f45-a40d-9174f46b4d1b",
                            TwoFactorEnabled = false,
                            UserName = "aliceaohnson@3s.com"
                        },
                        new
                        {
                            Id = "103",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ea4a3f62-ccc4-426e-ad2f-6c5251019178",
                            Email = "bobbrown@3s.com",
                            EmailConfirmed = true,
                            FullName = "Bob Brown",
                            LockoutEnabled = false,
                            NormalizedEmail = "BOBBROWN@3S.COM",
                            NormalizedUserName = "BOBBROWN@3S.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPe8A64wX5UwCmNqCR7UpNK7iSBpuqEg8cEt9Cdyb0B635WYMM6l6z2faM8hbko5Wg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "94a72b7f-8d26-4fb4-9ecb-77e20831a215",
                            TwoFactorEnabled = false,
                            UserName = "bobbrown@3s.com"
                        },
                        new
                        {
                            Id = "104",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6d143273-439e-4c8c-aa33-11ef4dc112e7",
                            Email = "charlieblack@3s.com",
                            EmailConfirmed = true,
                            FullName = "Charlie Black",
                            LockoutEnabled = false,
                            NormalizedEmail = "CHARLIEBLACK@3S.COM",
                            NormalizedUserName = "CHARLIEBLACK@3S.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOAa+vaeJuG8aWPjYlYjmwiQi8TSLzsrCw+X8gB2HK5vqIjfnXjh6GUBw0XYgftpdg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4302afac-3423-428d-aee8-4347f3c88a25",
                            TwoFactorEnabled = false,
                            UserName = "charlieblack@3s.com"
                        },
                        new
                        {
                            Id = "105",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "610bea20-86ee-4d88-be18-1bc969662b06",
                            Email = "dianawhite@3s.com",
                            EmailConfirmed = true,
                            FullName = "Diana White",
                            LockoutEnabled = false,
                            NormalizedEmail = "DIANAWHITE@3S.COM",
                            NormalizedUserName = "DIANAWHITE@3S.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMaIua5E9GfuiDQLGZKOM42jdRsoJRmbrNThwoDtgKu8ozJL37L/EiDLCQmBxEKr/g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "eafb9ce4-debf-42b2-b28e-c054691ab7d8",
                            TwoFactorEnabled = false,
                            UserName = "dianawhite@3s.com"
                        },
                        new
                        {
                            Id = "106",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4e1f2747-c805-4f54-ad6a-dd98181bc73d",
                            Email = "edwardgreen@3s.com",
                            EmailConfirmed = true,
                            FullName = "Edward Green",
                            LockoutEnabled = false,
                            NormalizedEmail = "EDWARDGREEN@3S.COM",
                            NormalizedUserName = "EDWARDGREEN@3S.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBKI7xVR/d1xW95gSm8fGqGXoX2KTZQd7tz015+G7Zoj2h1H4DHvZOTNAmMz4NBF/Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a380127b-b913-4d37-a6a1-bd729af5493e",
                            TwoFactorEnabled = false,
                            UserName = "edwardgreen@3s.com"
                        },
                        new
                        {
                            Id = "107",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "132f6d59-f3dd-49b7-9e0e-6e83a130b639",
                            Email = "janedoe@3s.com",
                            EmailConfirmed = true,
                            FullName = "Jane Doe",
                            LockoutEnabled = false,
                            NormalizedEmail = "JANEDOE@3S.COM",
                            NormalizedUserName = "JANEDOE@3S.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEM5Dn7B44BkI6IqPUFQwXuT4I9mzK6JPOGVe4samFoVTcrxxpo7wZ0FNSOjyVJeExQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ae3b5d05-a7b1-4898-8d2a-b34f938d9f96",
                            TwoFactorEnabled = false,
                            UserName = "janedoe@3s.com"
                        },
                        new
                        {
                            Id = "108",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c045da02-ab85-4b58-bec2-16c2f4d2138e",
                            Email = "michaeljordan@3s.com",
                            EmailConfirmed = true,
                            FullName = "Michael Jordan",
                            LockoutEnabled = false,
                            NormalizedEmail = "MICHAELJORDAN@3S.COM",
                            NormalizedUserName = "MICHAELJORDAN@3S.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEND34BKUn2pu0fL8OZndy1kymknEgSoMImoxTX+L7GwEc9r2ADloltFBkJZUZ+Gxcg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f27c1594-e00f-4b4a-a067-0726b7b0540d",
                            TwoFactorEnabled = false,
                            UserName = "michaeljordan@3s.com"
                        },
                        new
                        {
                            Id = "109",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4a93efee-846d-4f33-b03a-755d24cb00a8",
                            Email = "serenawilliams@3s.com",
                            EmailConfirmed = true,
                            FullName = "Serena Williams",
                            LockoutEnabled = false,
                            NormalizedEmail = "SERENAWILLIAMS@3S.COM",
                            NormalizedUserName = "SERENAWILLIAMS@3S.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOCv8or549gNfqDBEkDRgBGEKihw2NDX8GD2MCM/5IeVxASpEaW7JPhyyN9wvTfgaQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5f9cb9ea-800e-49a1-b254-d47ce7826b50",
                            TwoFactorEnabled = false,
                            UserName = "serenawilliams@3s.com"
                        },
                        new
                        {
                            Id = "110",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "910caaf9-41c1-47fb-bb64-dd3b2ca0b895",
                            Email = "rogerfederer@3s.com",
                            EmailConfirmed = true,
                            FullName = "Roger Federer",
                            LockoutEnabled = false,
                            NormalizedEmail = "ROGERFEDERER@3S.COM",
                            NormalizedUserName = "ROGERFEDERER@3S.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAxfQ0pQBpdWyk5lVTSEFuItZDe9+YcrutL9Br/4ePY53SL3pF8h9isUJeZAmLqWSw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a50a1557-353b-4bbf-88b8-51c91de54fb8",
                            TwoFactorEnabled = false,
                            UserName = "rogerfederer@3s.com"
                        });
                });

            modelBuilder.Entity("SmithSwimmingSchoolApp.Models.Coach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoachSex")
                        .HasColumnType("int");

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdentityUserId")
                        .IsUnique()
                        .HasFilter("[IdentityUserId] IS NOT NULL");

                    b.ToTable("Coaches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoachSex = 0,
                            IdentityUserId = "101",
                            Name = "John Smith",
                            PhoneNumber = "123-456-7890"
                        },
                        new
                        {
                            Id = 2,
                            CoachSex = 1,
                            IdentityUserId = "107",
                            Name = "Jane Doe",
                            PhoneNumber = "987-654-3210"
                        },
                        new
                        {
                            Id = 3,
                            CoachSex = 0,
                            IdentityUserId = "108",
                            Name = "Michael Jordan",
                            PhoneNumber = "333-444-5555"
                        },
                        new
                        {
                            Id = 4,
                            CoachSex = 1,
                            IdentityUserId = "109",
                            Name = "Serena Williams",
                            PhoneNumber = "777-888-9999"
                        },
                        new
                        {
                            Id = 5,
                            CoachSex = 1,
                            IdentityUserId = "110",
                            Name = "Roger Federer",
                            PhoneNumber = "555-666-7777"
                        });
                });

            modelBuilder.Entity("SmithSwimmingSchoolApp.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<int>("LevelCourse")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoachId = 1,
                            LevelCourse = 0,
                            Title = "Beginner Swimming"
                        },
                        new
                        {
                            Id = 2,
                            CoachId = 2,
                            LevelCourse = 1,
                            Title = "Advanced Swimming"
                        },
                        new
                        {
                            Id = 3,
                            CoachId = 3,
                            LevelCourse = 1,
                            Title = "Intermediate Swimming"
                        },
                        new
                        {
                            Id = 4,
                            CoachId = 4,
                            LevelCourse = 2,
                            Title = "Expert Swimming"
                        },
                        new
                        {
                            Id = 5,
                            CoachId = 5,
                            LevelCourse = 3,
                            Title = "Master Swimming"
                        });
                });

            modelBuilder.Entity("SmithSwimmingSchoolApp.Models.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("GroupingId")
                        .HasColumnType("int");

                    b.Property<int>("SwimmerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("GroupingId");

                    b.HasIndex("SwimmerId");

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            GroupingId = 1,
                            SwimmerId = 1
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 2,
                            GroupingId = 2,
                            SwimmerId = 2
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 3,
                            GroupingId = 3,
                            SwimmerId = 3
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 4,
                            GroupingId = 4,
                            SwimmerId = 4
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 5,
                            GroupingId = 5,
                            SwimmerId = 5
                        });
                });

            modelBuilder.Entity("SmithSwimmingSchoolApp.Models.Grouping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Places")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("Groupings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Beginner",
                            Places = 15,
                            StartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new TimeSpan(0, 0, 0, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            EndDate = new DateTime(2024, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Advanced",
                            Places = 10,
                            StartDate = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new TimeSpan(0, 0, 0, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            EndDate = new DateTime(2024, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Intermediate",
                            Places = 12,
                            StartDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new TimeSpan(0, 0, 0, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            EndDate = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Expert",
                            Places = 8,
                            StartDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new TimeSpan(0, 0, 0, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            EndDate = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Master",
                            Places = 6,
                            StartDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new TimeSpan(0, 0, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("SmithSwimmingSchoolApp.Models.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnrollmentId");

                    b.ToTable("Reports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Good progress",
                            EnrollmentId = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "Excellent performance",
                            EnrollmentId = 2
                        },
                        new
                        {
                            Id = 3,
                            Content = "Needs improvement",
                            EnrollmentId = 3
                        },
                        new
                        {
                            Id = 4,
                            Content = "Outstanding swimmer",
                            EnrollmentId = 4
                        },
                        new
                        {
                            Id = 5,
                            Content = "Beginner with potential",
                            EnrollmentId = 5
                        });
                });

            modelBuilder.Entity("SmithSwimmingSchoolApp.Models.Swimmer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SwimmerSex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdentityUserId")
                        .IsUnique()
                        .HasFilter("[IdentityUserId] IS NOT NULL");

                    b.ToTable("Swimmers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(2005, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdentityUserId = "102",
                            Name = "Alice Johnson",
                            PhoneNumber = "111-222-3333",
                            SwimmerSex = 1
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(2008, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdentityUserId = "103",
                            Name = "Bob Brown",
                            PhoneNumber = "444-555-6666",
                            SwimmerSex = 0
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(2010, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdentityUserId = "104",
                            Name = "Charlie Black",
                            PhoneNumber = "888-999-0000",
                            SwimmerSex = 0
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(2006, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdentityUserId = "105",
                            Name = "Diana White",
                            PhoneNumber = "222-333-4444",
                            SwimmerSex = 1
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(2007, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdentityUserId = "106",
                            Name = "Edward Green",
                            PhoneNumber = "555-777-8888",
                            SwimmerSex = 0
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SmithSwimmingSchoolApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SmithSwimmingSchoolApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmithSwimmingSchoolApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SmithSwimmingSchoolApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmithSwimmingSchoolApp.Models.Coach", b =>
                {
                    b.HasOne("SmithSwimmingSchoolApp.Models.ApplicationUser", "IdentityUser")
                        .WithOne()
                        .HasForeignKey("SmithSwimmingSchoolApp.Models.Coach", "IdentityUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("SmithSwimmingSchoolApp.Models.Course", b =>
                {
                    b.HasOne("SmithSwimmingSchoolApp.Models.Coach", "Coach")
                        .WithMany("Courses")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("SmithSwimmingSchoolApp.Models.Enrollment", b =>
                {
                    b.HasOne("SmithSwimmingSchoolApp.Models.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmithSwimmingSchoolApp.Models.Grouping", "Grouping")
                        .WithMany("Enrollments")
                        .HasForeignKey("GroupingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmithSwimmingSchoolApp.Models.Swimmer", "Swimmer")
                        .WithMany("Enrollments")
                        .HasForeignKey("SwimmerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Grouping");

                    b.Navigation("Swimmer");
                });

            modelBuilder.Entity("SmithSwimmingSchoolApp.Models.Report", b =>
                {
                    b.HasOne("SmithSwimmingSchoolApp.Models.Enrollment", "Enrollment")
                        .WithMany("Reports")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("SmithSwimmingSchoolApp.Models.Swimmer", b =>
                {
                    b.HasOne("SmithSwimmingSchoolApp.Models.ApplicationUser", "IdentityUser")
                        .WithOne()
                        .HasForeignKey("SmithSwimmingSchoolApp.Models.Swimmer", "IdentityUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("SmithSwimmingSchoolApp.Models.Coach", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("SmithSwimmingSchoolApp.Models.Course", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("SmithSwimmingSchoolApp.Models.Enrollment", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("SmithSwimmingSchoolApp.Models.Grouping", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("SmithSwimmingSchoolApp.Models.Swimmer", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
